### ISSUE TITLE
Iteration Plan for April 2020

### ISSUE THREAD

**Issue by cyrildewit** [LeerPlatform/api-application#1]
This plan captures my work in **April**.

## Plan Items

* [x] Add basic resource endpoints for the Course domain #3
* [x] Add basic resource endpoints for the Chapter domain #4
* [x] Add basic resource endpoints for the Topic domain #5
* [x] Add basic resource endpoints for the User domain #6
* [ ] Create authentication and authorization solution #9
