### ISSUE TITLE
Add basic resource endpoints for the Course domain

### ISSUE THREAD

**Issue by cyrildewit** [LeerPlatform/api-application#3]
## Todo

* [x] Add store course endpoint
* [x] Add update course endpoint
* [x] Add destroy course endpoint
