### ISSUE TITLE
Add basic resource endpoints for the Chapter domain

### ISSUE THREAD

**Issue by cyrildewit** [LeerPlatform/api-application#4]
## Todo

* [x] Add store chapter endpoint
* [x] Add update chapter endpoint
* [x] Add destroy chapter endpoint
