### ISSUE TITLE
Add basic resource endpoints for the Topic domain

### ISSUE THREAD

**Issue by cyrildewit** [LeerPlatform/api-application#5]
## Todo

* [x] Add show endpoint
* [x] Add store course endpoint
* [x] Add update course endpoint
* [x] Add destroy course endpoint
