### ISSUE TITLE
Add basic resource endpoints for the User domain

### ISSUE THREAD

**Issue by cyrildewit** [LeerPlatform/api-application#6]
## Todo

* [x] Add index user endpoint
* [x] Add show user endpoint
* [ ] ~Add store user endpoint~
* [x] Add destroy user endpoint
